//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaGloban.Modelo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int ID { get; set; }
        public Nullable<int> IDENTIFICACION { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<int> TIPOCONTRATO { get; set; }
        public Nullable<int> CELULAR { get; set; }
        public Nullable<double> SALARY { get; set; }
    }
}
