//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaGloban.Modelo.Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB_MASGLOBANEntities1 : DbContext
    {
        public DB_MASGLOBANEntities1()
            : base("name=DB_MASGLOBANEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public DbSet<TIPOCONTRATO> TIPOCONTRATO { get; set; }
    
        public virtual ObjectResult<SP_CONSULT_EMPLOYEES_Result> SP_CONSULT_EMPLOYEES(Nullable<int> cEDULA, Nullable<int> iNDICADOR)
        {
            var cEDULAParameter = cEDULA.HasValue ?
                new ObjectParameter("CEDULA", cEDULA) :
                new ObjectParameter("CEDULA", typeof(int));
    
            var iNDICADORParameter = iNDICADOR.HasValue ?
                new ObjectParameter("INDICADOR", iNDICADOR) :
                new ObjectParameter("INDICADOR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULT_EMPLOYEES_Result>("SP_CONSULT_EMPLOYEES", cEDULAParameter, iNDICADORParameter);
        }
    
        public virtual ObjectResult<SP_TYPE_CONTRACT_Result> SP_TYPE_CONTRACT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TYPE_CONTRACT_Result>("SP_TYPE_CONTRACT");
        }
    }
}
