//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaGloban.Modelo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOCONTRATO
    {
        public int ID { get; set; }
        public string TIPOCONTRATO1 { get; set; }
    }
}
